config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true, length: {minimum: 2, maximum: 36}
  validates :description, presence: true, length: {minimum: 2, maximum: 362}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def about
    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
      if @post.save
        flash[:success] = 'Post are succefully created'
        redirect_to post_path(@post)
      else
        render 'new'
      end
  end

  def show

  end

  def edit

  end

  def update
      if @post.update(post_params)
        flash[:success] = 'Post are succefully updated'
        redirect_to post_path(@post)
      else
        render 'edit'
      end
  end

  def destroy
    @post.destroy
    flash[:danger] = 'post succefully deleted'
    redirect_to posts_path(@post)
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">

    <small>
      Corpyright &copy; <a href="#">Complet Ruby in Rails Cource</a>
      by <a href="#">Serraj mohammed</a>
    </small>

    <nav>
      <ul>
      <li><%= link_to 'About', about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_form.html.erb
<%= render 'shared/errors', obj: @post %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@post, :html => {class: 'form-horizontal', role:'form'}) do |f| %>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :title %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :title, class: 'form-control', placeholder: 'Title of article', autofocus: true %>
            </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :description%>
          </div>
          <div class="col-sm-8">
            <%= f.text_area :description, rows:10, class: 'form-control', placeholder: 'Type a description', autofocus: true %>
          </div>
        </div>
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to 'Cancel request and return to articles listing', posts_path %> ]
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
    <div class='alert alert-<%= "#{name}" %>'>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div,msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- //////////////////////////-->
        <!-- ////////Embded Ruby /////////////// -->
      <!--<a class="navbar-brand" id="logo" href="#">ELEGENCE</a>-->
      <%= link_to 'ELEGENCE', root_path, class: 'navbar-brand', id: 'logo' %>


    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><%= link_to 'Articles', posts_path %></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'New Article', new_post_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ferari</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>


  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>
<%= link_to'Back to HOME page', root_path %>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>ALPHA BLOG</h1>
  <%= link_to 'Sign Up', '#', class: "btn btn-primary btn-lg btn-xlarge" %>
</div>

app/views/posts/edit.html.erb
<h1 align="center">Edit exicting Article</h1>
<%= render 'layouts/form' %>

app/views/posts/index.html.erb
<h1>INDEX page action</h1>
<%= link_to'Create a new post', new_post_path(@post) %>
<table>
  <tr>
    <td>Title</td>

    <td>Description</td>
  </tr>

  <% @posts.each do |posts| %>
  <tr>
    <td><%= posts.title %></td>

    <td><%= posts.description %></td>
    <td><%= link_to'edit', edit_post_path(posts) %></td>
    <td><%= link_to'show', post_path(posts) %></td>
    <td><%= link_to'delete', post_path(posts), method: :delete, data: {confirm: 'Are you sure ??'} %></td>
  </tr>

 <% end %>
</table>

<p>
  <%= link_to'Back to Home page', root_path %>
</p>

app/views/posts/new.html.erb
<<<<<<< HEAD
<h1 align="center ">Create Article</h1>
=======

<h1 align="center">Create Article</h1>
>>>>>>> styl_messages
<%= render 'layouts/form' %>

app/views/posts/show.html.erb
<h1>Showing exicting article</h1>

<p>Title <%= @post.title %></p>
<p>Description: <%= @post.description %></p>

<p>
  <%= link_to'Back to all posts listenner', posts_path %> | <%= link_to'edit this post', edit_post_path %>
</p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(obj.errors.count, 'error') %>
              prihibeted this article from being saved:
            </h2>
            <div class="panel-body">
              <ul>
                <%= obj.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>